<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_RequestStatueController.php" was generated by ProBot AI.
* Date: 25-Jul-23 10:36:58 AM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\RequestStatue;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class RequestStatueController extends Controller{
	public function index(){
		$requeststatues = RequestStatue::paginate(10);
		return view("pages.erp.requeststatue.index",["requeststatues"=>$requeststatues]);
	}
	public function create(){
		return view("pages.erp.requeststatue.create",[]);
	}
	public function store(Request $request){
		//RequestStatue::create($request->all());
		$requeststatue = new RequestStatue;

		$requeststatue->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$requeststatue = RequestStatue::find($id);
		return view("pages.erp.requeststatue.show",["requeststatue"=>$requeststatue]);
	}
	public function edit(RequestStatue $requeststatue){
		return view("pages.erp.requeststatue.edit",["requeststatue"=>$requeststatue,]);
	}
	public function update(Request $request,RequestStatue $requeststatue){
		//RequestStatue::update($request->all());
		$requeststatue = RequestStatue::find($requeststatue->id);

		$requeststatue->save();

		return redirect()->route("requeststatues.index")->with('success','Updated Successfully.');
	}
	public function destroy(RequestStatue $requeststatue){
		$requeststatue->delete();
		return redirect()->route("requeststatues.index")->with('success', 'Deleted Successfully.');
	}
}
?>
