<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_RequestTokenController.php" was generated by ProBot AI.
* Date: 25-Jul-23 10:42:35 AM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers\API;
use App\Http\Controllers\Controller;
use App\Models\RequestToken;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class RequestTokenController extends Controller{
	public function index(){
		$requesttokens = RequestToken::with(['status', 'customer'])->get();

		 return json_encode($requesttokens);
	}
	public function create(){
		return view("pages.erp.requesttoken.create",[]);
	}
	public function store(Request $request){
		//RequestToken::create($request->all());
		$requesttoken = new RequestToken;
		$requesttoken->id=$request->id;
		$requesttoken->customer_id=$request->customer_id;
		$requesttoken->item=$request->item;
		$requesttoken->problem=$request->problem;
		$requesttoken->status_id=$request->status_id;
date_default_timezone_set("Asia/Dhaka");
		$requesttoken->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$requesttoken->updated_at=date('Y-m-d H:i:s');

		$requesttoken->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$requesttoken = RequestToken::find($id);
		return view("pages.erp.requesttoken.show",["requesttoken"=>$requesttoken]);
	}
	public function edit(RequestToken $requesttoken){
		return view("pages.erp.requesttoken.edit",["requesttoken"=>$requesttoken,]);
	}
	public function update(Request $request,RequestToken $requesttoken){
		//RequestToken::update($request->all());
		$requesttoken = RequestToken::find($requesttoken->id);
		$requesttoken->id=$request->id;
		$requesttoken->customer_id=$request->customer_id;
		$requesttoken->item=$request->item;
		$requesttoken->problem=$request->problem;
		$requesttoken->status_id=$request->status_id;
date_default_timezone_set("Asia/Dhaka");
		$requesttoken->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$requesttoken->updated_at=date('Y-m-d H:i:s');

		$requesttoken->save();

		return redirect()->route("requesttokens.index")->with('success','Updated Successfully.');
	}
	public function destroy($id){
		$requesttoken=RequestToken::find($id);
		$requesttoken->delete();
		
	}
}
?>
